event_list ::= event* EOF
event    ::= event_start statement_list event_end
event_start ::= '{' NEWLINE
event_end ::= '}' NEWLINE
statement_list ::= statement*
statement ::= name_statement
           | popup_statement
           | image_statement
           | sound_statement
           | flag_statement
           | type_statement
name_statement ::= '#' 'NAME' '=' event_name
popup_statement ::= '#' 'POPUP' '=' popup_msg
image_statement ::= '#' 'IMAGE' '=' image_name
sound_statement ::= '#' 'SOUND' '=' sound_name
flag_statement ::= '#' 'FLAG' '=' flag_number
type_statement ::= '#' 'TYPE' '=' type_number
type_number ::= '0'
           | '1'
           | '2'
           | '3'
flag_number ::= '0'
           | '1'
sound_name ::= string
image_name ::= string
popup_msg ::= string
event_name ::= string
string   ::= STRING? EOL
_        ::= NEWLINE
           | Newline
           | LINE_COMMENT
           | WS
           | Whitespace
          /* ws: definition */

<?TOKENS?>

NEWLINE  ::= [#xd#xa]+
Newline  ::= #xD #xA?
           | #xA
INTEGER  ::= [0-9]+
LINE_COMMENT ::= ';' [^#xa#xd]*
EOL      ::= #xD #xA?
           | #xA
WS       ::= [ #xd#xa#x9]+
Whitespace ::= [ #x9]+
STRING   ::= [a-zA-Z0-9,;:'.* !<>{}()[@?=_"`+/#x5D#x2D#x23#x9]+
EOF      ::= $