
rulelist ::= rule_* EOF;
rule_    ::= lhs '::=' rhs;
lhs      ::= id_;
rhs      ::= alternatives;
alternatives ::= alternative ( '|' alternative )*;
alternative ::= element*;
element  ::= optional_
           | zeroormore
           | oneormore
           | text_
           | id_;
optional_ ::= '[' alternatives ']';
zeroormore ::= '{' alternatives '}';
oneormore ::= '(' alternatives ')';
text_    ::= ID;
id_      ::= '<' ruleid '>';
ruleid   ::= ID;
_        ::= WS;


ID       ::= [a-zA-Z] [a-zA-Z0-9 #x2D]+;
WS       ::= [ #xd#xa#x9];
EOF      ::= $;